development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

# development:
#   adapter: mysql2
#   encoding: utf8
#   database: dinosaur-account-dev
#   username: root
#   password: 
#   pool: 5


test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
    adapter: mysql2
    encoding: utf8
    database: dinosaur_accounts
    username: root
    password: 
    pool: 5
