development:
    adapter: mysql2
    encoding: utf8
    database: accounts
    username: root
    password:
    pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: accounts
  username: root
  password:
  pool: 5
